gText_Birch_Welcome::
	.string "Hola! Disculpa per fer-te esperar!\p"
	.string "Et done la benvinguda\n"
	.string "al món dels POKéMON!\p"
	.string "Em diuen ROURES.\p"
	.string "Però tot el món em coneix com el\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Açò és el que anomenem un “POKéMON”.\p"
	.string "$"

// You need to go to ../src/strings.c#L107 to translate this single line of OAK's speech.

gText_Birch_MainSpeech::
	.string "El món es troba habitat per unes\n"
	.string "criatures que anomenem POKéMON.\p"
	.string "La gent i els POKéMON viuen en armonia,\n"
	.string "ajudant-se entre ells.\p"
	.string "Alguns juguen amb ells. Uns altres\n"
	.string "els utilitzen per a lluitar.\p"
	.string "Però encara no ho sabem tot sobre ells.\p"
	.string "Encara hi ha molts misteris per\n"
	.string "resoldre. Per això em dedique a\l"
	.string "estudiar els POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I tu qui eres?$"

gText_Birch_BoyOrGirl::
	.string "Eres un xic?\n"
	.string "O una xica?$"

gText_Birch_Difficulty::
	.string "Molt bé…\p"
	.string "I… com creus que serà\n"
	.string "aquesta aventura?$"

gText_Birch_LockDifficulty::
	.string "Si et cal canviar la DIFICULTAT\n"
	.string "pots obrir el MENÚ D'OPCIONS i\l"
	.string "canviar-la allà.\p"
	.string "També la pots bloquejar, si vols.\n"
	.string "Vols bloquejar la DIFICULTAT\l"
	.string "que has triat?\p"
	.string "Ja no la podràs tornar a canviar.$"

gText_Birch_Challenge::
	.string "Oh, de veres?\p"
	.string "D'acord, amb això aclarit…\n"
	.string "Creus que tindràs molts REPTES\l"
	.string "durant el viatge?\p"
	.string "I com et diuen?$"

gText_Birch_WhatsYourName::
	.string "I ara, com m'havies dit que\n"
	.string "et diuen?$"

gText_Birch_SoItsPlayer::
	.string "Has dit {PLAYER}{KUN}, veritat?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, estàs a punt?\p"
	.string "La teua aventura està a un pas de\n"
	.string "començar.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Et trobaràs moments divertits, però\n"
	.string "també reptes complicats.\p"
	.string "T'espera un món d'aventures i somnis\n"
	.string "amb els POKéMON! Molta sort!\p"
	.string "Ens veurem més endavant!\p"
	.string "$"
