gText_Birch_Welcome::
	.string "Hola! Disculpa per fer-te esperar!\p"
	.string "Et done la benvinguda al món dels POKéMON!\p"
	.string "Em diuen ROURES.\p"
	.string "Però la gent em diu\n"
	.string "el PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Açò és el que anomenem «POKéMON».\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "El món es troba habitat per diverses\n"
	.string "criatures conegudes com a POKéMON.\p"
	.string "La gent i els POKéMON viuen en armonia,\n"
	.string "ajudant-se entre ells.\p"
	.string "Alguns juguen amb els POKéMON,\n"
	.string "altres lluiten amb ells. \p"
	.string "Però encara no ho sabem tot\n"
	.string "sobre els POKéMON. \p"
	.string "Encara hi ha molts misteris\n"
	.string "que resoldre. Per això estudie els\l"
	.string "POKéMON cada dia.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "I tu qui eres?$"

gText_Birch_BoyOrGirl::
	.string "Eres un xic?\n"
	.string "O una xica?$"

gText_Birch_Difficulty::
	.string "Molt bé…\p"
	.string "I… com creus que serà\n"
	.string "aquesta aventura?$"

gText_Birch_LockDifficulty::
	.string "Si et cal canviar la DIFICULTAT\n"
	.string "pots obrir el MENÚ D'OPCIONS i\l"
	.string "canviar-la allà.\p"
	.string "També la pots bloquejar, si vols.\n"
	.string "Vols bloquejar la DIFICULTAT\l"
	.string "que has triat?\p"
	.string "Ja no la podràs canviar després.$"

gText_Birch_Challenge::
	.string "Oh, de veres?\p"
	.string "D'acord, amb això aclarit…\n"
	.string "Creus que tindràs molts REPTES\l"
	.string "durant el viatge?\p"
	.string "I com et diuen?$"

gText_Birch_WhatsYourName::
	.string "I ara, com m'havies dit que\n"
	.string "et diuen?$"

gText_Birch_SoItsPlayer::
	.string "Ah! Així que eres {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, estàs a punt?\p"
	.string "La teua pròpia aventura està a punt\n"
	.string "de començar.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Et trobaràs diversions, però també\n"
	.string "reptes complicats.\p"
	.string "T'espera un món ple de somnis i\n"
	.string "aventures amb els POKéMON! Endavant!\p"
	.string "Ens veurem més endavant!\p"
	.string "$"
