Text_PictureBookShelf:
	.string "Hi ha llibres amb il·lustracions\n"
    .string "de POKéMON.$"

Text_BookShelf:
	.string "Hi ha llibres de moltes temàtiques.$"

Text_PokemonCenterBookShelf:
	.string "Són revistes de POKéMON!\n"
	.string "LA REVISTA DEL POKéAMIC…\p"
	.string "MANUAL PER A ENTRENADORS…\n"
	.string "POKéMON ENCISADORS…$"

Text_Vase:
	.string "Pareix un gerro molt car…\n"
	.string "A veure què hi ha a dins…\p"
	.string "Vaja, està buit.$"

Text_EmptyTrashCan:
	.string "Està buida.$"

Text_ShopShelf:
	.string "La prestatgeria està plena d'articles\n"
	.string "per als POKéMON.$"

Text_Blueprint:
	.string "És una espècie de plànol…\n"
	.string "Que complicat!$"
