gText_ObtainedTheItem::
	.string "Has rebut: {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Tens la MOTXILLA plena…$"

gText_PutItemInPocket::
	.string "Ho guardes en la\n"
	.string "BUTXACA {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "Trobes una unitat de {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Llàstima!\n"
	.string "Tens la MOTXILLA plena…$"

gText_PlayerPutItemInBag::
	.string "Ho guardes en\n"
	.string "la MOTXILLA.$"

gText_ObtainedTheDecor::
	.string "Has rebut: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Llàstima! No t'hi caben més\n"
	.string "unitats de {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "S'ha enviat al PC.$"

gText_PutItemInPC::
	.string "Ho guardes en el PC ja que\n"
	.string "tens la MOTXILLA plena.$"

gText_TooBadBagAndPCAreFull::
	.string "Llàstima!\n"
	.string "Tens la MOTXILLA i el PC plens…$"
