	.align 2
gText_ConfirmSave::
	.string "Vols guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ja hi ha una partida guardada.\n"
	.string "Vols sobreescriure-la?$"

gText_SavingDontTurnOff::
	.string "GUARDANT…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha guardat la partida.$"

gText_DifferentSaveFile::
	.string "ATENCIÓ!\p"
	.string "Ja tens una partida diferent\n"
	.string "guardada.\p"
	.string "Si guardes, tot el progrés de\n"
	.string "l'altra partida es perdrà per\l"
	.string "complet.\p"
	.string "Segur que vols guardar i\n"
	.string "esborrar l'altra partida?$"

gText_SaveError::
	.string "Error en guardar.\p"
	.string "Intercanvia la memòria\n"
	.string "de recuperació.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANT…\n"
	.string "NO APAGUES LA CONSOLA.$"
